In [2]:
import pandas as pd
df1 = pd.read_excel("PCBs.xlsx", sheet_name = 0, index_col=0).T
df1

Amostra,Chlorination 1,Chlorination 2,Chlorination 3,Chlorination 4,Chlorination 5,Chlorination 6,Chlorination 7,Chlorination 8,Chlorination 9,Chlorination 10,Soma
CA203I,0.384438,0.384438,0.384438,96.555436,788.297709,1932.154390,818.191604,65.200677,0.384438,0.384438,3702.322005
CA230I,0.406372,0.406372,0.406372,104.616385,1096.277633,3588.865410,1563.962939,125.487646,0.406372,0.406372,6481.241873
CA260I,0.379997,0.379997,0.379997,199.072807,1681.334549,5901.367989,2562.380301,168.065055,0.379997,0.379997,10514.120687
CA286I,0.417021,0.417021,0.417021,90.043203,592.787202,1782.598542,1020.550802,88.508566,0.417021,0.417021,3576.573421
CA288I,0.348092,0.348092,0.348092,23.781676,148.343080,363.185742,190.698970,0.348092,0.348092,0.348092,728.098023
CA289I,0.410374,0.410374,0.410374,21.093237,123.801707,263.082731,150.443204,3.660538,0.410374,0.410374,564.133290
CA290I,0.430219,0.430219,0.430219,51.350886,391.843056,1047.237997,597.504732,54.276372,0.430219,0.430219,2144.364137
CA303I,0.359919,0.359919,0.359919,29.398215,200.921394,493.031961,244.457242,16.297149,0.359919,0.359919,985.905557
CA304I,0.369768,0.369768,0.369768,123.768673,1095.932554,3313.296850,1891.362225,165.434107,0.369768,0.369768,6591.643248
CA318I,0.355619,0.355619,0.355619,61.251778,551.123755,1674.566145,1086.230441,103.157895,0.355619,0.355619,3478.108108
CA254I,0.409212,0.409212,0.409212,55.783805,420.260914,1154.207520,663.611216,55.390961,0.409212,0.409212,2351.300476
CA275I,0.417906,0.417906,0.417906,62.301494,439.420280,1416.301695,1033.967437,134.532446,0.417906,0.417906,3088.612885
CA281I,0.411184,0.411184,0.411184,66.924342,554.062500,1817.976974,1114.424342,134.473684,0.411184,0.411184,3689.917763
CA295I,0.405180,0.405180,0.405180,67.308471,560.266446,2285.781430,1710.928510,202.281973,0.405180,0.405180,4828.592729
CA307I,0.385814,0.385814,0.385814,35.927035,287.524306,1043.041452,719.049971,71.699744,0.385814,0.385814,2159.171579

In [6]:
df2 = pd.read_excel("PCBs.xlsx", sheet_name = 1, index_col=0).T
df2

Amostra,Chlorination 1,Chlorination 2,Chlorination 3,Chlorination 4,Chlorination 5,Chlorination 6,Chlorination 7,Chlorination 8,Chlorination 9,Chlorination 10,Soma
CA203O,0.404008,0.404008,0.404008,70.701357,540.546218,1112.265676,389.641241,5.866193,0.404008,0.404008,2121.040724
CA230O,0.368677,0.368677,0.368677,101.622180,1227.813007,5212.711989,2694.337118,232.620557,0.368677,0.368677,9470.948238
CA260O,0.504948,0.504948,0.504948,449.181983,5543.667946,15210.401939,15496.748132,691.577459,7.715613,0.504948,37401.312866
CA286O,0.343407,0.343407,0.343407,43.406593,314.546703,803.956044,368.035714,13.076923,0.343407,0.343407,1544.739011
CA288O,0.413839,0.413839,0.413839,22.860454,153.550737,338.420791,166.793577,0.413839,0.413839,0.413839,684.108591
CA289O,0.391604,0.391604,0.391604,18.264411,91.243734,149.671053,73.652882,0.391604,0.391604,0.391604,335.181704
CA290O,0.355164,0.355164,0.355164,50.106549,356.897287,857.110385,412.189231,19.434579,0.355164,0.355164,1697.513851
CA303O,0.394011,0.394011,0.394011,34.247439,236.658786,581.292356,287.706856,24.933018,0.394011,0.394011,1166.808511
CA304O,0.365711,0.365711,0.365711,174.956115,1519.836161,4059.903452,1746.342891,105.207724,0.365711,0.365711,7608.074898
CA318O,0.336610,0.336610,0.336610,58.947085,437.444459,1139.814191,598.249630,49.037296,0.336610,0.336610,2285.175710
CA254O,0.357291,0.357291,0.357291,45.590316,337.282589,939.589258,535.564734,21.723285,0.357291,0.357291,1881.536637
CA275O,0.409038,0.409038,0.409038,51.326102,338.110898,969.943880,525.057674,56.365451,0.409038,0.409038,1942.849196
CA281O,0.443553,0.443553,0.443553,67.597537,607.064918,2220.925075,1458.101946,178.148786,0.443553,0.443553,4534.056030
CA295O,0.364745,0.364745,0.364745,59.803621,507.652354,1625.333742,997.038269,88.428824,0.364745,0.364745,3280.080536
CA307O,0.376121,0.376121,0.376121,34.949148,256.078113,829.451766,476.229163,24.237227,0.376121,0.376121,1622.826022

In [7]:
from numpy.random import seed
from numpy.random import randn
from scipy.stats import mannwhitneyu
# seed the random number generator
seed(1)
# generate two independent samples
data1 = df1["Soma"]
data2 = df2["Soma"]
# compare samples
stat, p = mannwhitneyu(data1, data2)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=137.000, p=0.320
Same distribution (fail to reject H0)

In [9]:
df3 = pd.read_excel("DDTs.xlsx", sheet_name = 0, index_col=0).T
df3

Amostras     4,4' DDE   2,4' DDD    4,4' DDD    4,4' DDT         Soma
CA203I     758.788252   0.384438  186.098724  199.369522  1144.640935
CA230I    1271.716515   0.406372  395.448635  182.493498  1850.065020
CA260I    2441.100471  21.386229  693.540052  290.530476  3446.557228
CA286I     494.703832   4.987573   73.645932   62.236234   635.573571
CA288I      95.864662  12.768031   13.255361   16.040100   137.928154
CA289I      58.929744   0.410374    0.410374    0.410374    60.160867
CA290I     308.466701   0.430219   43.779040   30.648770   383.324729
CA303I     126.432479   0.359919   20.760150   18.989346   166.541895
CA304I    1118.370064  14.154711  236.503476   55.894099  1424.922349
CA318I     270.611664   0.355619   61.294452   24.068279   356.330014
CA254I     373.136038   0.409212   58.484605   44.784181   476.814038
CA275I     435.207783   0.417906   82.110260   40.219317   557.955267
CA281I     638.898026   0.411184  105.723684   46.069079   791.101974
CA295I     673.473688   0.405180  103.256025   47.114309   824.249202
CA307I     287.925553   3.271706   58.612920   15.509738   365.319917

In [10]:
df4 = pd.read_excel("DDTs.xlsx", sheet_name = 1, index_col=0).T
df4

Amostras     4,4' DDE   2,4' DDD     4,4' DDD    4,4' DDT         Soma
CA203O     576.858436   0.404008   189.819005  125.420168   892.501616
CA230O    1663.397729   0.368677   506.444477  203.716266  2373.927149
CA260O    7292.466168  63.219552  1330.801858  760.715007  9447.202585
CA286O     125.096154   6.318681    16.098901   33.076923   180.590659
CA288O      77.172654   0.413839     0.413839   14.053965    92.054296
CA289O     296.553885   0.391604    41.901629    0.391604   339.238722
CA290O     129.137662   0.355164    26.694133   24.279017   180.465975
CA303O     835.334909   8.510638   170.827423   14.862096  1029.535067
CA304O     331.816852   0.365711    62.068461   83.747806   477.998830
CA318O       0.336610   0.336610     0.336610   21.071765    22.081594
CA254O     313.758557   0.357291    55.694502   33.385260   403.195610
CA275O     370.097678   0.409038    65.576989   37.926013   474.009719
CA281O     750.332665   0.443553   117.736813   53.528024   922.041055
CA295O     572.445689   0.364745    91.901198   41.756029   706.467662
CA307O     269.528194   0.376121    50.054161   13.119095   333.077571

In [11]:
# seed the random number generator
seed(1)
# generate two independent samples
data3 = df3["Soma"]
data4 = df4["Soma"]
# compare samples
stat, p = mannwhitneyu(data3, data4)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=122.000, p=0.709
Same distribution (fail to reject H0)

In [12]:
df5 = pd.read_excel("CHLs.xlsx", sheet_name = 0, index_col=0).T
df5

Client Sample ID,Heptachlor Epoxide,Alpha Chlordane,Cis-Nonachlor,Trans-Nonachlor,Soma
CA203I,39.105028,0.384438,22.835614,45.932646,108.257727
CA230I,0.406372,0.406372,87.500000,99.138492,187.451235
CA260I,98.480012,0.379997,101.808786,59.112327,259.781122
CA286I,0.417021,0.417021,19.049525,25.755225,45.638793
CA288I,0.348092,0.348092,0.348092,0.348092,1.392370
CA289I,0.410374,0.410374,0.410374,0.410374,1.641497
CA290I,0.430219,0.430219,0.430219,9.946653,11.237309
CA303I,0.359919,0.359919,0.359919,6.795278,7.875036
CA304I,0.369768,0.369768,50.436326,48.720603,99.896465
CA318I,0.355619,0.355619,13.982930,11.209104,25.903272
CA254I,15.189956,0.409212,12.390945,18.038073,46.028187
CA275I,18.103708,0.417906,15.780148,17.735950,52.037712
CA281I,19.736842,0.411184,21.759868,29.523026,71.430921
CA295I,18.686893,0.405180,21.442116,33.078880,73.613069
CA307I,11.204050,0.385814,10.339825,15.432575,37.362264

In [13]:
df6 = pd.read_excel("CHLs.xlsx", sheet_name = 1, index_col=0).T
df6

Client Sample ID,Heptachlor Epoxide,Alpha Chlordane,Cis-Nonachlor,Trans-Nonachlor,Soma
CA203O,0.404008,0.404008,16.919845,30.898513,48.626374
CA230O,37.457602,0.368677,76.625866,42.855036,157.307182
CA260O,169.905070,29.549586,272.732781,412.744900,884.932337
CA286O,0.343407,0.343407,0.343407,0.343407,1.373626
CA288O,0.413839,0.413839,0.413839,0.413839,1.655355
CA289O,0.391604,0.391604,0.391604,15.899123,17.073935
CA290O,0.355164,0.355164,0.355164,7.188521,8.254013
CA303O,0.394011,0.394011,25.563436,36.327817,62.679275
CA304O,0.365711,0.365711,15.301346,14.906378,30.939146
CA318O,0.336610,0.336610,0.336610,0.336610,1.346439
CA254O,13.577053,0.357291,11.004559,14.548885,39.487788
CA275O,15.494363,0.409038,11.780297,15.494363,43.178062
CA281O,17.546972,0.443553,26.063197,37.258485,81.312208
CA295O,16.705330,0.364745,21.957660,28.406355,67.434091
CA307O,0.376121,0.376121,12.366853,15.315641,28.434736

In [14]:
data5 = df5["Soma"]
data6 = df6["Soma"]
# compare samples
stat, p = mannwhitneyu(data5, data6)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=129.000, p=0.507
Same distribution (fail to reject H0)

In [19]:
df7 = pd.read_excel("OCs.xlsx", sheet_name = 0, index_col=0).T
df7

Client Sample ID  Hexachlorobenzene    Dieldrin      Mirex
CA203I                    48.193142    0.384438  54.605567
CA230I                    24.317295    0.406372  47.821847
CA260I                    45.827633  347.241222  80.604955
CA286I                    35.563562    0.417021  89.092395
CA288I                    13.311055    0.348092  11.013645
CA289I                    12.344058    0.410374  11.506894
CA290I                    29.426949    0.430219  53.622440
CA303I                    11.632594    0.359919  15.433343
CA304I                    36.133708   86.318592  91.258690
CA318I                    15.448080    0.355619  56.870555
CA254I                    30.036174   40.675691  29.446909
CA275I                    27.214068   48.761325  56.333790
CA281I                    36.036184   61.743421  57.023026
CA295I                    38.378632   57.940714  84.763618
CA307I                    22.315504    0.385814  32.485571

In [18]:
df8 = pd.read_excel("OCs.xlsx", sheet_name = 1, index_col=0).T
df8

Client Sample ID  Hexachlorobenzene    Dieldrin       Mirex
CA203O                    41.936005    0.404008   20.410472
CA230O                    33.461141    0.368677   89.883498
CA260O                   127.348011  654.110281  272.773177
CA286O                    13.145604    0.343407   19.340659
CA288O                     9.899023    0.413839    8.640953
CA289O                    22.697368    0.391604    0.391604
CA290O                    13.212104    0.355164   26.438415
CA303O                    35.145784    0.394011   15.334909
CA304O                    18.110006   36.541837   52.881802
CA318O                     0.336610    0.336610   23.589605
CA254O                    21.466036   34.642923   16.349631
CA275O                    24.395033   42.752663   26.734731
CA281O                    39.529479   65.344286   72.050813
CA295O                    39.377891   40.603434   33.965072
CA307O                    20.701691   23.635434   19.106939

In [17]:
data7 = df7["Hexachlorobenzene"]
data8 = df8["Hexachlorobenzene"]
# compare samples
stat, p = mannwhitneyu(data7, data8)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=126.000, p=0.590
Same distribution (fail to reject H0)

In [20]:
data9 = df7["Dieldrin"]
data10 = df8["Dieldrin"]
# compare samples
stat, p = mannwhitneyu(data9, data10)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=125.000, p=0.619
Same distribution (fail to reject H0)

In [21]:
data11 = df7["Mirex"]
data12 = df8["Mirex"]
# compare samples
stat, p = mannwhitneyu(data11, data12)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=151.000, p=0.115
Same distribution (fail to reject H0)

In [4]:
df9 = pd.read_excel("%Lipid.xlsx", sheet_name = 1, index_col=0).T
df9

 ID     % Lipid
CA203I   65.030
CA203O   61.880
CA230I   61.520
CA230O   67.810
CA260I   65.790
CA260O   49.510
CA286I   59.949
CA286O   72.800
CA288I   71.820
CA288O   60.410
CA289I   60.920
CA289O   63.840
CA290I   58.110
CA290O   70.390
CA303I   69.460
CA303O   63.450
CA304I   67.610
CA304O   68.360
CA318I   70.300
CA318O   74.270
CA254I   61.093
CA254O   69.971
CA275I   59.822
CA275O   61.119
CA281I   60.800
CA281O   56.363
CA295I   61.701
CA295O   68.541
CA307I   64.798
CA307O   66.468

In [5]:
df10 = pd.read_excel("%Lipid.xlsx", sheet_name = 2, index_col=0).T
df10

 ID     % Lipid
CA203O   61.880
CA230O   67.810
CA260O   49.510
CA286O   72.800
CA288O   60.410
CA289O   63.840
CA290O   70.390
CA303O   63.450
CA304O   68.360
CA318O   74.270
CA254O   69.971
CA275O   61.119
CA281O   56.363
CA295O   68.541
CA307O   66.468

In [10]:
from numpy.random import seed
from numpy.random import randn
from scipy.stats import mannwhitneyu
# seed the random number generator

# generate two independent samples
data13 = df9["% Lipid"]
data14 = df10["% Lipid"]
# compare samples
stat, p = mannwhitneyu(data13, data14)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=200.500, p=0.563
Same distribution (fail to reject H0)

In [8]:
df11 = pd.read_excel("%Lipid.xlsx", sheet_name = 4, index_col=0).T
df11

ID      % Lipid
CA203I   65.030
CA230I   61.520
CA260I   65.790
CA286I   59.949
CA288I   71.820
CA289I   60.920
CA290I   58.110
CA303I   69.460
CA304I   67.610
CA318I   70.300
CA254I   61.093
CA275I   59.822
CA281I   60.800
CA295I   61.701
CA307I   64.798

In [9]:
df12 = pd.read_excel("%Lipid.xlsx", sheet_name = 5, index_col=0).T
df12

ID      % Lipid
CA203O   61.880
CA230O   67.810
CA260O   49.510
CA286O   72.800
CA288O   60.410
CA289O   63.840
CA290O   70.390
CA303O   63.450
CA304O   68.360
CA318O   74.270
CA254O   69.971
CA275O   61.119
CA281O   56.363
CA295O   68.541
CA307O   66.468

In [12]:
data15 = df11["% Lipid"]
data16 = df12["% Lipid"]
# compare samples
stat, p = mannwhitneyu(data15, data16)
print('Statistics=%.3f, p=%.3f' % (stat, p))
# interpret
alpha = 0.05
if p > alpha:
	print('Same distribution (fail to reject H0)')
else:
	print('Different distribution (reject H0)')

Statistics=88.000, p=0.320
Same distribution (fail to reject H0)